title: portfolio
description: My Personal webPage
author: Aditya Gupta
github: https://github.com/addyag93
about: I am Researcher at University of Delhi. Currently 
disqus_shortname: Personal Webpage
google_analytics: UA-XXXXXXXX-Y
avatar_url: /static/img/avatar.jpg

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-facebook
      link: "#"
    - icon: fa-twitter
      link: #"https://twitter.com/agusmakmun6"
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/addyag93"
    - icon: fa-stack-exchange
      link: "#"
    - icon: fa-github
      link: "https://github.com/addyag93"

share:
  twitter_username: addyag93
  fb_appid: 1749788565247320

urls:
    - text: About Me
      url: /about/
    - text: My Projects
      url: /projects/

url: "https://addyag93.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
